### PR TITLE
typo fixed

### PR DESCRIPTION
**Pull request by chruetli**
typo fixed

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
I am not a Qt member, but I am aware that Qt does not accept contributions via GitHub pull requests.

Since this PR was opened, your proposed change was already made to the qtwebengine dev branch as part of 170fc1c2cb43318817552f1a1bed42b5cdc6eb36

**Comment by chruetli** [comment]
See comment above

**Comment by ericmarceau-rogers** [comment]
Trying to submit an issue, but I am not able to locate where I can do that.

I mistakenly submitted the problem on another [Qt related site](https://bugreports.qt.io/browse/QTWB-66).

How can I do this?

**Comment by The-Compiler** [comment]
@ericmarceau-rogers The Qt bugtracker (bugreports.qt.io) is indeed the correct place to report bugs for Qt projects. However, you should have chosen "Qt (QTBUG)" as project, not Qt Webbrowser which is something different. I moved the bug accordingly.

**Pull request closed without merging**
